#!/bin/bash
shopt -s extglob
now=$(date +"%m_%d_%Y")

cd ~/Downloads/
if [[ $(ls !(*.zip|*.iso|old|zips|isos) 2>/dev/null | wc -l ) != 0 ]]; then
	if [[ ! -d old/$now ]]; then
		echo -ne "\e[1;31m"		
		mkdir -v old/$now/
	fi
	echo -ne "\e[1;36m"
	mv -v !(*.zip|*.iso|old|zips|isos) old/$now/
fi
echo -ne "\e[1;33m"
mv -v *.zip zips/ 2>/dev/null
echo -ne "\e[1;35m"
mv -v *.iso isos/ 2>/dev/null
echo -ne "\e[0m"

shopt -u extglob