#!/bin/bash

# Config #
PROG_NAME="cleanfolder"
DEFAULT_PATH="/home/$USER/Downloads"
# Config #

if [[ -z $1 ]]; then
	cd $DEFAULT_PATH
else
	if [[ $1 = "-h" ]]; then
		echo " "
		echo " Usage:"
		echo "  <$PROG_NAME> 	 -- Cleans $DEFAULT_PATH directory."
		echo "  <$PROG_NAME DIR_NAME> -- Cleans DIR_NAME."
		echo "  <$PROG_NAME -h> 	 -- Show this help dialog."
		echo " "
		exit
	else
		cd $1
	fi
fi

shopt -s extglob
year=$(date +"%Y")

for FILENAME in *
do
	#if [[ -f $FILENAME ]]; then
		date=$(stat -c %Y "$FILENAME" | awk '{print strftime("%d_%m_%Y", $1)}')
		mkdir -vp "$date"
		find . -maxdepth 1 -name $FILENAME \! -name "*$year" -exec mv {} "$date" \;
	#fi
done 