#!/bin/bash
##-----------
## A very simple search script with option-based interface
##-----------
## TESTE
##Depth values can be changed:
DEEP=10
MEDIUM=5
SHALLOW=1

if [[ "$1" = "-h" ]]; then
		echo "-----------------------------------------------------------------------------------"		
		echo "	Usage:"
		echo "	<simplesearch -h>   show this help dialog"
		echo "	"
		echo "	<simplesearch -a>   search all files that contain search string"
		echo "	<simplesearch -s>   search for all files that begins with search string"
		echo "	<simplesearch -e>   search only for files with exact name"
		echo "	The program uses the -s parameter as default if none is given"
		echo "	"		
		echo "	First input the name of the file you want to search for."
		echo "	Then you will be prompted for the directory in which to search in."
		echo "	The depth decides how many subfolders the program will search through:"
		echo "	"
		echo "	Shallow = $SHALLOW"
		echo "	Medium  = $MEDIUM"
		echo "	Deep    = $DEEP"
		echo "	"
		echo "	Lastly you can select what type of file you are looking for."
		echo "	"
		echo "	NOTE: The search function is case-sensitive."
		echo "-----------------------------------------------------------------------------------"
		exit
fi

while true
do
	echo " "
	echo "Use <simplesearch -h> for help"
	echo "Enter 'q' at any time to quit"
	echo -e "Name of object to search for: \c"
	read var1
	if [[ $var1 = q ]]
		then
			exit
	fi

	if [[ "$1" = "-a" ]]; then
		NAME=$(echo *"$var1"*)
	elif [[ "$1" = "-e" ]]; then
		NAME=$(echo "$var1")
	else
		NAME=$(echo "$var1"*)
	fi
	echo -e "Enter directory to search in: \c"
	read PA
	if [[ $PA = q ]]
		then
			exit
	fi
	echo 'Please enter depth of search: '
	OPTIONS="Shallow Medium Deep"
	select opt in $OPTIONS
	do
		 case $opt in
			  "Shallow")
				   DEPTH="$SHALLOW"
					break
				   ;;
			  "Medium")
				   DEPTH="$MEDIUM"
					break
				   ;;
			  "Deep")
				   DEPTH="$DEEP"
					break
				   ;;
			  *) echo invalid option;;
		 esac
	done
	
	echo 'Please enter filetype: '
	OPTIONS="Directory File All"
	select opt in $OPTIONS
	do
		 case $opt in
			  "Directory")
				   TYPE="-type d"
					break
				   ;;
			  "File")
				   TYPE="-type f"
					break
				   ;;
			  "All")
				   TYPE=""
					break
				   ;;
			  *) echo invalid option;;
		 esac
	done
	echo ""
	echo -ne "\e[1;32m"
	find $PA -maxdepth $DEPTH $TYPE -name $NAME 2>/dev/null | awk '{n++;print}END{print n}'; echo -en "\033[1A\033[5C results found"
	echo -ne "\e[0;0m"
done

exit